apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.helloService.name }}
  labels:
    app: {{ .Values.helloService.name }}
spec:
  replicas: {{ .Values.helloService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.helloService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.helloService.name }}
    spec:
      containers:
      - name: {{ .Values.helloService.name }}
        image: "{{ .Values.ecrregistry }}/{{ .Values.helloService.image }}:{{ .Values.tag }}"
        ports:
        - containerPort: {{ .Values.helloService.port }}
        env:
        - name: PORT
          value: "{{ .Values.helloService.port }}"
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.profileService.name }}
  labels:
    app: {{ .Values.profileService.name }}
spec:
  replicas: {{ .Values.profileService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.profileService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.profileService.name }}
    spec:
      containers:
      - name: {{ .Values.profileService.name }}
        image: "{{ .Values.ecrregistry }}/{{ .Values.profileService.image }}:{{ .Values.tag }}"
        ports:
        - containerPort: {{ .Values.profileService.port }}
        env:
        - name: PORT
          value: "{{ .Values.profileService.port }}"
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URL
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - name: {{ .Values.frontend.name }}
        image: "{{ .Values.ecrregistry }}/{{ .Values.frontend.image }}:{{ .Values.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.port }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}