apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.helloService.name }}
            port:
              number: {{ .Values.helloService.port }}
      - path: /profile
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.profileService.name }}
            port:
              number: {{ .Values.profileService.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.port }}