apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helloService.name }}
spec: 
  type: ClusterIP
  selector:
    app: {{ .Values.helloService.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.helloService.port }}
    targetPort: {{ .Values.helloService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.profileService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.profileService.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.profileService.port }}
    targetPort: {{ .Values.profileService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.service.name }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}