helloService:
  name: hello-service
  image: public.ecr.aws/l5r9g0t4/mern/hello:6
  replicas: 1
  port: 3001

profileService:
  name: profile-service
  image: public.ecr.aws/l5r9g0t4/mern/profile:6
  replicas: 1
  port: 3002
  mongoUrl: "mongodb+srv://tm_docker:Ri1OcidhdUoQdmTF@herovired-ppmcad.kncn7uu.mongodb.net/mernapp"

frontend:
  name: frontend
  image: public.ecr.aws/l5r9g0t4/mern/frontend:6
  replicas: 1
  port: 80

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  name: my-service-account

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  name: my-ingress
  enabled: true
  host: myapp.example.com